Add `tabbable` config for StaticMath
desmosinc/mathquill pull request #302
Opened 2024-09-14 05:12 UTC by jared-hughes

Changes:
- Adds `tabbable` config.
- Allows `.focus()` on StaticMath. It focuses the textarea and selects the entire range.

When `tabbable` is set to true on a static math field, the textarea is permanently present and part of the page's tab order.

2024-09-15 16:32 UTC, eluberoff requested changes
I'm intrigued by this approach!

One blocker:
* calling "focus" doesn't work (you can't then e.g. copy), because the textarea is still detached

One possible cleanup:
* I'm not sure that we need the midSelection logic, and can instead look at whether anything's selected

I much prefer your "tabbable" flag, and your example on the frontpage, and your test.

I'm going to try cherry-picking all of them onto the other branch that keeps the textarea in the DOM always and just adjusts its tabindex.

Then we can pick between after

2024-09-15 16:32 UTC, eluberoff commented on src/publicapi.ts
> +      this.__controller.scrollHoriz();
I think we might only want to do this for editable

2024-09-15 16:32 UTC, eluberoff commented on src/services/focusBlur.ts
> +      if (!(this instanceof Controller_keystroke)) return;
playing around on another branch, I think another approach to this could be to check if anything's selected, since we'll only focus on mouse events once something is.

```
    if (!this.cursor.selection || this.cursor.selection.isCleared()) {
      this.cursor.controller.selectAll();
    }```

2024-09-15 16:32 UTC, eluberoff commented on src/publicapi.ts
> +        this.__controller.selectAll();
this isn't working for me if `tabbable` isn't set to true, because we don't parent the textarea

2024-09-16 21:21 UTC, jared-hughes commented
Closing this in favor of #303.

2024-09-16 21:21 UTC, closed without merging